package com.lancewu.greendao3gradleplugin.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.lancewu.greendao3gradleplugin.bean.A;
import com.lancewu.greendao3gradleplugin.bean.B;
import com.lancewu.greendao3gradleplugin.bean.C;
import com.lancewu.greendao3gradleplugin.bean.D;
import com.lancewu.greendao3gradleplugin.bean.E;
import com.lancewu.greendao3gradleplugin.bean.F;
import com.lancewu.greendao3gradleplugin.bean.G;
import com.lancewu.greendao3gradleplugin.bean.H;
import com.lancewu.greendao3gradleplugin.bean.I;
import com.lancewu.greendao3gradleplugin.bean.J;
import com.lancewu.greendao3gradleplugin.bean.K;

import com.lancewu.greendao3gradleplugin.dao.ADao;
import com.lancewu.greendao3gradleplugin.dao.BDao;
import com.lancewu.greendao3gradleplugin.dao.CDao;
import com.lancewu.greendao3gradleplugin.dao.DDao;
import com.lancewu.greendao3gradleplugin.dao.EDao;
import com.lancewu.greendao3gradleplugin.dao.FDao;
import com.lancewu.greendao3gradleplugin.dao.GDao;
import com.lancewu.greendao3gradleplugin.dao.HDao;
import com.lancewu.greendao3gradleplugin.dao.IDao;
import com.lancewu.greendao3gradleplugin.dao.JDao;
import com.lancewu.greendao3gradleplugin.dao.KDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig aDaoConfig;
    private final DaoConfig bDaoConfig;
    private final DaoConfig cDaoConfig;
    private final DaoConfig dDaoConfig;
    private final DaoConfig eDaoConfig;
    private final DaoConfig fDaoConfig;
    private final DaoConfig gDaoConfig;
    private final DaoConfig hDaoConfig;
    private final DaoConfig iDaoConfig;
    private final DaoConfig jDaoConfig;
    private final DaoConfig kDaoConfig;

    private final ADao aDao;
    private final BDao bDao;
    private final CDao cDao;
    private final DDao dDao;
    private final EDao eDao;
    private final FDao fDao;
    private final GDao gDao;
    private final HDao hDao;
    private final IDao iDao;
    private final JDao jDao;
    private final KDao kDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        aDaoConfig = daoConfigMap.get(ADao.class).clone();
        aDaoConfig.initIdentityScope(type);

        bDaoConfig = daoConfigMap.get(BDao.class).clone();
        bDaoConfig.initIdentityScope(type);

        cDaoConfig = daoConfigMap.get(CDao.class).clone();
        cDaoConfig.initIdentityScope(type);

        dDaoConfig = daoConfigMap.get(DDao.class).clone();
        dDaoConfig.initIdentityScope(type);

        eDaoConfig = daoConfigMap.get(EDao.class).clone();
        eDaoConfig.initIdentityScope(type);

        fDaoConfig = daoConfigMap.get(FDao.class).clone();
        fDaoConfig.initIdentityScope(type);

        gDaoConfig = daoConfigMap.get(GDao.class).clone();
        gDaoConfig.initIdentityScope(type);

        hDaoConfig = daoConfigMap.get(HDao.class).clone();
        hDaoConfig.initIdentityScope(type);

        iDaoConfig = daoConfigMap.get(IDao.class).clone();
        iDaoConfig.initIdentityScope(type);

        jDaoConfig = daoConfigMap.get(JDao.class).clone();
        jDaoConfig.initIdentityScope(type);

        kDaoConfig = daoConfigMap.get(KDao.class).clone();
        kDaoConfig.initIdentityScope(type);

        aDao = new ADao(aDaoConfig, this);
        bDao = new BDao(bDaoConfig, this);
        cDao = new CDao(cDaoConfig, this);
        dDao = new DDao(dDaoConfig, this);
        eDao = new EDao(eDaoConfig, this);
        fDao = new FDao(fDaoConfig, this);
        gDao = new GDao(gDaoConfig, this);
        hDao = new HDao(hDaoConfig, this);
        iDao = new IDao(iDaoConfig, this);
        jDao = new JDao(jDaoConfig, this);
        kDao = new KDao(kDaoConfig, this);

        registerDao(A.class, aDao);
        registerDao(B.class, bDao);
        registerDao(C.class, cDao);
        registerDao(D.class, dDao);
        registerDao(E.class, eDao);
        registerDao(F.class, fDao);
        registerDao(G.class, gDao);
        registerDao(H.class, hDao);
        registerDao(I.class, iDao);
        registerDao(J.class, jDao);
        registerDao(K.class, kDao);
    }
    
    public void clear() {
        aDaoConfig.clearIdentityScope();
        bDaoConfig.clearIdentityScope();
        cDaoConfig.clearIdentityScope();
        dDaoConfig.clearIdentityScope();
        eDaoConfig.clearIdentityScope();
        fDaoConfig.clearIdentityScope();
        gDaoConfig.clearIdentityScope();
        hDaoConfig.clearIdentityScope();
        iDaoConfig.clearIdentityScope();
        jDaoConfig.clearIdentityScope();
        kDaoConfig.clearIdentityScope();
    }

    public ADao getADao() {
        return aDao;
    }

    public BDao getBDao() {
        return bDao;
    }

    public CDao getCDao() {
        return cDao;
    }

    public DDao getDDao() {
        return dDao;
    }

    public EDao getEDao() {
        return eDao;
    }

    public FDao getFDao() {
        return fDao;
    }

    public GDao getGDao() {
        return gDao;
    }

    public HDao getHDao() {
        return hDao;
    }

    public IDao getIDao() {
        return iDao;
    }

    public JDao getJDao() {
        return jDao;
    }

    public KDao getKDao() {
        return kDao;
    }

}
